import { ArrowRight, Building2, Check, Dumbbell, GraduationCap, Ruler, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import Seo from '../components/Seo'
import Reveal from '../components/Reveal'
import SectionHeading from '../components/SectionHeading'
import { BUSINESS } from '../data/site'
import schoolPoster from '../assets/images/school-furniture-reference.jpg'
import sportsFacility from '../assets/images/sports-facility-night.jpg'

export default function About() {
  return <>
    <Seo title="About Hafiz Lifelong Interior | Furniture & Sports Solutions" description="Learn about Hafiz Lifelong Interior's school furniture, educational infrastructure, artificial grass, sports nets and customized project solutions." path="/about"/>
    <section className="bg-navy pb-16 pt-36 text-white sm:pb-20 sm:pt-40"><div className="container-shell"><div className="eyebrow">About Hafiz</div><h1 className="max-w-4xl font-display text-5xl font-extrabold leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">Building better spaces through quality & design.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/70 sm:text-lg">A business positioned across school furniture and sports infrastructure, with solutions shaped around practical requirements.</p></div></section>
    <section className="bg-white py-16 sm:py-20 lg:py-24"><div className="container-shell grid gap-10 lg:grid-cols-2 lg:items-center"><Reveal><img src={schoolPoster} alt="School furniture reference" className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-soft"/></Reveal><Reveal delay={.08}><SectionHeading eyebrow="What the business covers" title={<>Furniture + infrastructure, <span className="text-lime">under one roof.</span></>} copy="The supplied references connect educational furniture with sports infrastructure, artificial grass and sports netting. The website keeps those two sides visible without inventing company history or unsupported credentials."/><div className="grid gap-3 sm:grid-cols-2">{[['School furniture',GraduationCap],['Sports infrastructure',Dumbbell],['Artificial grass',ShieldCheck],['Customized solutions',Ruler]].map(([x,I])=>{const Icon=I as typeof ShieldCheck;return <div key={String(x)} className="rounded-2xl border border-slate-200 p-4"><Icon size={20} className="text-lime"/><div className="mt-3 text-sm font-extrabold text-navy">{String(x)}</div></div>})}</div></Reveal></div></section>
    <section className="bg-paper py-16 sm:py-20"><div className="container-shell grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><Reveal><div className="eyebrow">Business positioning</div><h2 className="section-title">Designed for educational and sports spaces.</h2><p className="section-copy">The supplied material names schools, colleges, coaching centres, institutes, libraries, offices and sports facilities as relevant applications.</p><div className="mt-7 space-y-3">{['School & college furniture','Sports nets and boundary nets','Artificial grass for sports applications','Box cricket and football turf categories'].map(x=><div key={x} className="flex items-center gap-3 text-sm font-bold text-navy"><Check size={18} className="text-lime"/>{x}</div>)}</div></Reveal><Reveal delay={.08}><img src={sportsFacility} alt="Completed sports facility at night" loading="lazy" className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-soft"/></Reveal></div></section>
    <section className="bg-navy py-14 text-white"><div className="container-shell flex flex-col justify-between gap-6 lg:flex-row lg:items-center"><div><div className="eyebrow">Direct consultation</div><h2 className="font-display text-3xl font-extrabold">Based in {BUSINESS.shortLocation}.</h2><p className="mt-2 text-sm text-white/60">{BUSINESS.phone}</p></div><Link to="/get-quote" className="btn-primary">Discuss your requirement <ArrowRight size={17}/></Link></div></section>
  </>
}
