import { Mail, MapPin, MessageCircle, Phone, ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import Seo from '../components/Seo'
import InquiryForm from '../components/InquiryForm'
import Reveal from '../components/Reveal'
import { BUSINESS } from '../data/site'
import { whatsappUrl } from '../lib/whatsapp'

export default function Contact() {
  return <>
    <Seo title="Contact Hafiz Lifelong Interior | Meerut" description="Contact Hafiz Lifelong Interior in Pabla, Incholi, Meerut for school furniture, artificial grass, sports nets, box cricket and sports infrastructure inquiries." path="/contact"/>
    <section className="bg-navy pb-16 pt-36 text-white sm:pb-20 sm:pt-40"><div className="container-shell"><div className="eyebrow">Contact</div><h1 className="max-w-4xl font-display text-5xl font-extrabold tracking-tight sm:text-6xl lg:text-7xl">Let’s talk about your space.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/70 sm:text-lg">Reach Hafiz Lifelong Interior directly or send the requirement through the inquiry form.</p></div></section>
    <section className="bg-paper py-16 sm:py-20"><div className="container-shell grid gap-7 lg:grid-cols-[.72fr_1.28fr]"><Reveal><div className="rounded-3xl bg-navy p-7 text-white shadow-soft sm:p-8"><div className="eyebrow">Hafiz Lifelong Interior</div><h2 className="font-display text-3xl font-extrabold">Direct contact</h2><div className="mt-7 space-y-5"><a href={`tel:${BUSINESS.phone.replace(/\s/g,'')}`} className="flex gap-3 text-sm font-bold hover:text-lime"><Phone size={19} className="shrink-0 text-lime"/>{BUSINESS.phone}</a><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="flex gap-3 text-sm font-bold hover:text-lime"><MessageCircle size={19} className="shrink-0 text-lime"/>WhatsApp</a><div className="flex gap-3 text-sm font-bold text-white/80"><MapPin size={19} className="shrink-0 text-lime"/>{BUSINESS.location}</div>{BUSINESS.email ? <a href={`mailto:${BUSINESS.email}`} className="flex gap-3 break-all text-sm font-bold hover:text-lime"><Mail size={19} className="shrink-0 text-lime"/>{BUSINESS.email}</a> : <div className="rounded-2xl border border-white/10 bg-white/5 p-4 text-xs leading-5 text-white/55">Business email is intentionally configurable because the supplied reference poster does not provide a sufficiently reliable transcription.</div>}</div><div className="mt-8 border-t border-white/10 pt-6 text-xs text-white/50">Udyam Registration: <span className="font-bold text-white/70">{BUSINESS.udyam}</span></div></div></Reveal><Reveal delay={.08}><div><div className="mb-5"><h2 className="font-display text-2xl font-extrabold text-navy">Send an inquiry</h2><p className="mt-1 text-sm text-slate-600">Tell us the product or facility you are planning.</p></div><InquiryForm/></div></Reveal></div></section>
    <section className="bg-white py-14"><div className="container-shell flex flex-col justify-between gap-5 rounded-3xl bg-lime p-7 sm:p-9 lg:flex-row lg:items-center"><div><div className="text-xs font-extrabold uppercase tracking-[.16em] text-navy/60">Prefer a quick conversation?</div><h2 className="mt-2 font-display text-2xl font-extrabold text-navy">Call or WhatsApp the team.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><a href={`tel:${BUSINESS.phone.replace(/\s/g,'')}`} className="btn-dark"><Phone size={16}/> Call Now</a><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="btn-ghost"><MessageCircle size={16}/> WhatsApp</a><Link to="/get-quote" className="btn-ghost">Full quote form <ArrowRight size={16}/></Link></div></div></section>
  </>
}
